# $FreeBSD$

PORTNAME=        python-vlc
PORTVERSION=     3.0.6108
CATEGORIES=      python
py27_PKGNAMESUFFIX=  -py27
py35_PKGNAMESUFFIX=  -py35
py36_PKGNAMESUFFIX=  -py36
py37_PKGNAMESUFFIX=  -py37

USE_GITHUB=      yes
GH_ACCOUNT=      oaubert 
GH_PROJECT=      python-vlc
GH_TAGNAME=      fff0541

MAINTAINER=      hukadan@protonmail.com
COMMENT=         ctypes-based bindings for the native libvlc API of the VLC video player. 
LICENSE=         LGPL21+ 

NO_ARCH=         yes
USES=            python
USE_PYTHON=      autoplist distutils allflavors

PYSETUP=         generated/3.0/setup.py

.include <bsd.port.mk>
