# $FreeBSD$

PORTNAME=        python-vlc
DISTVERSION=     3.0.6108
CATEGORIES=      python

MAINTAINER=      hukadan@protonmail.com
COMMENT=         ctypes-based bindings for the native libvlc API of the VLC video player. 

USES=            python
USE_PYTHON=      autoplist distutils

.include <bsd.port.mk>
